version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - app-network
    volumes:
      - ollama_data:/root/.ollama

  ollama-pull:
    image: ollama/ollama:latest
    container_name: ollama-pull
    depends_on:
      - ollama
    networks:
      - app-network
    entrypoint: /bin/sh
    command:
      - -c
      - |
        sleep 5
        ollama pull gpt-oss:latest
        echo "Model pulled successfully"
    restart: "no"

  web:
    build:
      context: .
      dockerfile: Dockerfile # Make sure this path is correct from your project root
    # --- All properties below were moved out of the 'build' block ---
    env_file:
      - .env # <-- Correctly loads your .env file into the container
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - ./:/app # <-- Mounts your local code for --reload to work
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]

volumes:
  db_data:
  ollama_data:

networks:
  app-network:
    driver: bridge
